baseURL = 'https://tbspweb.github.io/tbsp-site/'
languageCode = 'en-us'
title = 'Tahoe Backcountry Ski Patrol'
theme = 'PaperMod'

[params]
description = "Promotes fun, safe, and responsible winter recreation by providing education, delivering outreach, and rendering assistance to the Tahoe Region winter sports community."

[[params.socialIcons]]
name = "wiki"
url = "http://wiki.tbsp.org"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Join Us"
url = "http://wiki.tbsp.org/TBSP_Introduction"
weight = 2
